name: Generate static org-roam-ui page
on:
  push:
    branches:
      - master
jobs:
  main:
    permissions:
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: Publish org-roam-ui page
        uses: ikoamu/publish-org-roam-ui@v0.2.0
        with:
          org-roam-db-filename: org-roam.db
          deploy-to-pages: true
          site-title: Brain
